"""add article paywall column

Revision ID: 0f42abaa8399
Revises: c6b68bc513a1
Create Date: 2026-05-06 06:28:52.255159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f42abaa8399'
down_revision: Union[str, Sequence[str], None] = 'c6b68bc513a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. server_default backfills existing rows with FALSE
    so the NOT NULL constraint can be added in one step on a populated table."""
    op.add_column(
        'articles',
        sa.Column('paywall', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'paywall')
    # ### end Alembic commands ###
